GET http://localhost:5555/stats
Accept: application/json

###
POST http://localhost:5555/tasks
Content-Type: application/json

{
  "ID": "266592cd-960d-4091-981c-8c25c44b1018",
  "State": 2,
  "Task": {
    "State": 1,
    "ID": "266592cd-960d-4091-981c-8c25c44b1018",
    "Image": "strm/helloworld-http"
  }
}

###
GET http://localhost:5555/tasks


###
DELETE http://localhost:5555/tasks/266592cd-960d-4091-981c-8c25c44b1018
Accept: application/json

###
POST http://localhost:5555/tasks
Content-Type: application/json

{
  "ID": "6be4cb6b-61d1-40cb-bc7b-9cacefefa60c",
  "State": 2,
  "Task": {
    "State": 1,
    "ID": "21b23589-5d2d-4731-b5c9-a97e9832d021",
    "Name": "test-chapter-5",
    "Image": "strm/helloworld-http"
  }
}
